Hotel/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from app.views import *

urlpatterns = [
	path('admin/', admin.site.urls),
    path('hotel/', home),
    path('addimage/', addimageopen),
    path('saveimage/', saveimage),
    path('show/', show),
    path('about/', about),
    path('adminlogin/', adminLogin),
    path('adminlogin/check/', admincheck),
    path('hoteldatasave/', hoteldatasave),
    path('addhotel/', addhotel),
    path('addcategory/', addcategory),
    path('addeventcategory/', addeventcategory),
    path('addfacility/', addfacility),
    path('savefacility/', facilitiesdatasave),
    path('adddecoration/', adddecoration),
    path('savedecoration/', savedecoration),
    path('browsevenues/', browsevenues),
    path('moreinfo/', moreInfo),
]
if settings.DEBUG:
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)	

app/models.py
from django.db import models
import datetime
class ImgData(models.Model):
	Hotel_ID=models.CharField(max_length=100)
	Image_Type=models.CharField(max_length=50)
	image=models.ImageField(upload_to="images/")
	class Meta:
		db_table="ImageData"
class HotelInfo(models.Model):
	Reg_Date=models.DateField(("Date"), default=datetime.date.today)
	Hotel_ID=models.CharField(max_length=100)
	Hotel_Name=models.CharField(max_length=200)
	Hotel_Address=models.TextField()
	Hotel_City=models.CharField(max_length=50)
	Hotel_Area=models.CharField(max_length=100)
	Hotel_State=models.CharField(max_length=100)
	Hotel_Phone=models.CharField(max_length=50)
	Hotel_Email=models.CharField(max_length=50)
	Hotel_PriceType=models.CharField(max_length=50)
	Hotel_Price=models.CharField(max_length=50)
	Hotel_Min_Gathering=models.CharField(max_length=50)
	Hotel_Max_Gathering=models.CharField(max_length=50)
	Hotel_Category=models.CharField(max_length=50)
	Hotel_Event_Type=models.CharField(max_length=50)
	Status=models.CharField(max_length=50)
	class Meta:
		db_table="HotelInfo"

class CategoryInfo(models.Model):
	Category_Name=models.CharField(max_length=100)
	class Meta:
		db_table="CategoryInfo"

class EventCategory(models.Model):
	Category_Name=models.CharField(max_length=100)
	class Meta:
		db_table="EventCategory"

class FacilityInfo(models.Model):
	Hotel_ID=models.CharField(max_length=100)
	Stage=models.CharField(max_length=10)
	DJ=models.CharField(max_length=10)
	Pool=models.CharField(max_length=10)
	Seating_Style=models.CharField(max_length=50)
	Caterer=models.CharField(max_length=10)
	Rental_Charge=models.CharField(max_length=10)
	Decoration_Included=models.CharField(max_length=10)
	Crokery_Included=models.CharField(max_length=10)
	Hall_Included=models.CharField(max_length=10)
	AC_Rooms=models.CharField(max_length=10)
	NON_AC_Rooms=models.CharField(max_length=10)
	Other_Terms=models.TextField()
	class Meta:
		db_table="FacilityInfo"

class DecorationTypeInfo(models.Model):
	Hotel_ID=models.CharField(max_length=100)
	Decoration_Name=models.CharField(max_length=100)
	Decoration_Price=models.CharField(max_length=100)
	class Meta:
		db_table="DecorationTypeInfo"

app/templates/adddecoration.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>VenuesHub-Admin Desk</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
       
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/aos.css" %}">
    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>
    
   <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="index.html">VenuesHub</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        
      </div>
    </div>
  </nav>
  <!-- END nav -->


  
  <div class="block-30 block-30-sm item" style="background-image: url('{% static "images/bg_3.jpg" %}');" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-10">
          <span class="subheading-sm">venueshub</span>
          <h2 class="heading">Admin Desk</h2>
        </div>
      </div>
    </div>
  </div>

    
  

  <div class="site-section">
    <div class="container">
      <div class="row block-9">
        <div class="col-md-6 pr-md-5">
          <h1>Add Decoration Type to Venue Here</h1>
          <form action="/savedecoration/" method="POST">
            <div class="form-group">
              <label>Select Venue</label>
              <select name="venuename" class="form-control px-3 py-3" style="height:50px;" required>
                {% for x in venuename %}
                  <option value="{{ x|safe }}">{{ x|safe }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-group">
              <input type="text" name="decorationname" class="form-control px-3 py-3" placeholder="Decoration Name" required>
            </div>
            <div class="form-group">
              <input type="number" name="decorationprice" class="form-control px-3 py-3" placeholder="Decoration Price" required>
            </div>
            <div class="form-group">
              <input type="submit" value="ADD" class="btn btn-primary py-3 px-5">
            </div>
          </form>
          </div>

        <!--  <div class="col-md-6" id="map"></div> -->  
      </div>
    </div>
  </div>


        
<!--  <div class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-7 section-heading">
            <span class="subheading-sm">Reviews</span>
            <h2 class="heading">Customer Reviews</h2>
          </div>
        </div>
        <!--<div class="row">
          <div class="col-md-6 col-lg-4">

            <div class="block-33">
              <div class="vcard d-flex mb-3">
                <div class="image align-self-center"><img src="{% static "images/person_3.jpg" %}" alt="Person here"></div>
                <div class="name-text align-self-center">
                  <h2 class="heading">Martin Newmansfield</h2>
                  <span class="meta">Satisfied Customer</span>
                </div>
              </div>
              <div class="text">
                <blockquote>
                  <p>&rdquo; Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga aliquid. Atque dolore esse veritatis iusto eaque perferendis non dolorem fugiat voluptatibus vitae error ad itaque inventore accusantium tempore dolores sunt. &ldquo;</p>
                </blockquote>
              </div>
            </div>

          </div>
          <div class="col-md-6 col-lg-4">

            <div class="block-33">
              <div class="vcard d-flex mb-3">
                <div class="image align-self-center"><img src="{% static "images/person_2.jpg" %}" alt="Person here"></div>
                <div class="name-text align-self-center">
                  <h2 class="heading">Nancy Green</h2>
                  <span class="meta">Satisfied Customer</span>
                </div>
              </div>
              <div class="text">
                <blockquote>
                  <p>&rdquo; Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga aliquid. Atque dolore esse veritatis iusto eaque perferendis non dolorem fugiat voluptatibus vitae error ad itaque inventore accusantium tempore dolores sunt. &ldquo;</p>
                </blockquote>
              </div>
            </div>

          </div>
          <div class="col-md-6 col-lg-4">

            <div class="block-33">
              <div class="vcard d-flex mb-3">
                <div class="image align-self-center"><img src="{% static "images/person_1.jpg" %}" alt="Person here"></div>
                <div class="name-text align-self-center">
                  <h2 class="heading">Elizabeth Charles</h2>
                  <span class="meta">Satisfied Customer</span>
                </div>
              </div>
              <div class="text">
                <blockquote>
                  <p>&rdquo; Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga aliquid. Atque dolore esse veritatis iusto eaque perferendis non dolorem fugiat voluptatibus vitae error ad itaque inventore accusantium tempore dolores sunt. &ldquo;</p>
                </blockquote>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>-->

   <footer class="footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-6 col-lg-4">
          <h3 class="heading-section">About Us</h3>
          <p class="mb-5">Our motive is to provide customer to book unique spaces for corporate and private events including weddings, parties, meetings, get together, dinners, lunch and breakfast events as well as summer & christmas parties. Find the best event venues. View images and find best prices.</p>
          <p><a href="#" class="btn btn-primary px-4">Know More</a></p>
        </div>
        <div class="col-md-6 col-lg-4">
          <h3 class="heading-section">Blog</h3>
          <div class="block-21 d-flex mb-4">
            <figure class="mr-3">
              <img src="{% static "images/banquets.jpg" %}" alt="" class="img-fluid">
            </figure>
            <div class="text">
              <h3 class="heading"><a href="#">Our Luxury Banquets</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> May 29, 2018</a></div>
                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
              </div>
            </div>
          </div>

          <div class="block-21 d-flex mb-4">
            <figure class="mr-3">
              <img src="{% static "images/hotel1.jpg" %}" alt="" class="img-fluid">
            </figure>
            <div class="text">
              <h3 class="heading"><a href="#">Our Luxury Hotels</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> May 29, 2018</a></div>
                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
              </div>
            </div>
          </div>

          <div class="block-21 d-flex mb-4">
            <figure class="mr-3">
              <img src="{% static "images/restraunt1.jpg" %}" alt="" class="img-fluid">
            </figure>
            <div class="text">
              <h3 class="heading"><a href="#">Our Luxury Restaurants</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> May 29, 2018</a></div>
                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="block-23">
            <h3 class="heading-section">Contact Info</h3>
              <ul>
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+91 7417358703</span></a></li>
                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@venueshub.in</span></a></li>
                <li><span class="icon icon-globe"></span><span class="text">www.venueshub.in</span></li>
              </ul>
            </div>
        </div>
        
        
      </div>
        <div class="col-md-12 text-left">
          <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
           Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved @ Venueshub.in
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
  </footer>

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  
  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
  <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
  <script src="{% static "js/jquery.stellar.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
  <script src="{% static "js/bootstrap-datepicker.js" %}"></script>
  
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static "js/google-map.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>
  {{ alert|safe }}
  </body>
</html>

app/templates/addimage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>VenuesHub-Admin Desk</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
       
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/aos.css" %}">
    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>
    
   <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="index.html">VenuesHub</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        
      </div>
    </div>
  </nav>
  <!-- END nav -->


  
  <div class="block-30 block-30-sm item" style="background-image: url('{% static "images/bg_3.jpg" %}');" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-10">
          <span class="subheading-sm">venueshub</span>
          <h2 class="heading">Admin Desk</h2>
        </div>
      </div>
    </div>
  </div>

    
  

  <div class="site-section">
    <div class="container">
      <div class="row block-9">
        <div class="col-md-6 pr-md-5">
          <h1>Add Images to Venue Here</h1>
          <form action="/saveimage/" method="POST" enctype="multipart/form-data">
            <div class="form-group">
              <label>Select Venue</label>
              <select name="venuename" class="form-control px-3 py-3" style="height:50px;" required>
                {% for x in venuename %}
                  <option value="{{ x|safe }}">{{ x|safe }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-group">
              <label>Select Image Type</label>
              <select name="itype" class="form-control px-3 py-3" style="height:60px;" required>
                <option value="Cover">Cover Image</option>
                <option value="Slides">Slides</option>
              </select>
            </div>
            <div class="form-group">
              <label>Select Image</label>
              <ul class="errorlist"><li>This field is required.</li></ul>
              <input type="file" name="image" accept="image/*" required id="id_image">
            </div>
            <div class="form-group">
              <input type="submit" value="ADD" class="btn btn-primary py-3 px-5">
            </div>
          </form>
          </div>

        <!--  <div class="col-md-6" id="map"></div> -->  
      </div>
    </div>
  </div>


   <footer class="footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-6 col-lg-4">
          <h3 class="heading-section">About Us</h3>
          <p class="mb-5">Our motive is to provide customer to book unique spaces for corporate and private events including weddings, parties, meetings, get together, dinners, lunch and breakfast events as well as summer & christmas parties. Find the best event venues. View images and find best prices.</p>
          <p><a href="#" class="btn btn-primary px-4">Know More</a></p>
        </div>
        <div class="col-md-6 col-lg-4">
          <h3 class="heading-section">Blog</h3>
          <div class="block-21 d-flex mb-4">
            <figure class="mr-3">
              <img src="{% static "images/banquets.jpg" %}" alt="" class="img-fluid">
            </figure>
            <div class="text">
              <h3 class="heading"><a href="#">Our Luxury Banquets</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> May 29, 2018</a></div>
                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
              </div>
            </div>
          </div>

          <div class="block-21 d-flex mb-4">
            <figure class="mr-3">
              <img src="{% static "images/hotel1.jpg" %}" alt="" class="img-fluid">
            </figure>
            <div class="text">
              <h3 class="heading"><a href="#">Our Luxury Hotels</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> May 29, 2018</a></div>
                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
              </div>
            </div>
          </div>

          <div class="block-21 d-flex mb-4">
            <figure class="mr-3">
              <img src="{% static "images/restraunt1.jpg" %}" alt="" class="img-fluid">
            </figure>
            <div class="text">
              <h3 class="heading"><a href="#">Our Luxury Restaurants</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> May 29, 2018</a></div>
                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="block-23">
            <h3 class="heading-section">Contact Info</h3>
              <ul>
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+91 7417358703</span></a></li>
                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@venueshub.in</span></a></li>
                <li><span class="icon icon-globe"></span><span class="text">www.venueshub.in</span></li>
              </ul>
            </div>
        </div>
        
        
      </div>
        <div class="col-md-12 text-left">
          <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
           Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved @ Venueshub.in
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
  </footer>

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  
  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
  <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
  <script src="{% static "js/jquery.stellar.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
  <script src="{% static "js/bootstrap-datepicker.js" %}"></script>
  
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static "js/google-map.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>
  {{ alert|safe }}
  </body>
</html>

app/templates/image.html
<html>
<head>
<title>Image Upload</title>
</head>
{% load static %}
<body>
<form method="POST" action="/save/" enctype="multipart/form-data">
	<tr><th><label for="id_image">Image:</label></th>
			<td><ul class="errorlist"><li>This field is required.</li></ul>
			<input type="file" name="image" accept="image/*" required id="id_image"></td></tr>
	<input type="submit" value="Upload">
</form>
<img src="{{ path|safe }}">
</body>
</html>